In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel('eating habit.xlsx')
df

,Class,Age,I avoid eating when am hungry,I cut my food into small pieces,"I particularly avoid food with high carbonhydrate(bread,rice,potatoes etc)",I take longer time than others to eat my meals,I avoid food and drink with sugar content,I like my stomach empty,I fast to avoid eating
0,1,14,Always,Always,Always,Always,Always,Always,Always
1,1,14,Always,Always,Always,Always,Always,Always,Always
2,1,14,Always,Always,Always,Always,Always,Always,Always
3,1,14,Always,Always,Always,Always,Always,Always,Always
4,1,14,Always,Always,Always,Always,Always,Often,Always
...,...,...,...,...,...,...,...,...,...
402,0,23,Never,Never,Never,Never,Never,Never,Never
403,0,23,Never,Never,Never,Never,Never,Never,Never
404,0,23,Never,Never,Never,Never,Never,Never,Never
405,0,23,Never,Never,Never,Never,Never,Never,Never
406,0,23,Never,Never,Never,Never,Never,Never,Never

In [3]:
df.Class.unique()

array([1, 0], dtype=int64)

In [4]:
df.Age.unique()

array([14, 15, 16, 17, 18, 19, 20, 21, 22, 23], dtype=int64)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 407 entries, 0 to 406
Data columns (total 9 columns):
 #   Column                                                                      Non-Null Count  Dtype
---  ------                                                                      --------------  -----
 0   Class                                                                       407 non-null    int64
 1   Age                                                                         407 non-null    int64
 2   I avoid eating when am hungry                                               407 non-null    object
 3   I cut my food into small pieces                                             407 non-null    object
 4   I particularly avoid food with high carbonhydrate(bread,rice,potatoes etc)  407 non-null    object
 5   I take longer time than others to eat my meals                              407 non-null    object
 6   I avoid food and drink with sugar content                                   407 non-null    object
 7   I like my stomach empty                                                     407 non-null    object
 8   I fast to avoid eating                                                      407 non-null    object
dtypes: int64(2), object(7)
memory usage: 28.7+ KB

#### Our data is clean

### let's seperate the numerical datatypes from objects

In [6]:
numeric = df.select_dtypes(np.number)
numeric

     Class  Age
0        1   14
1        1   14
2        1   14
3        1   14
4        1   14
..     ...  ...
402      0   23
403      0   23
404      0   23
405      0   23
406      0   23

[407 rows x 2 columns]

In [7]:
objects = df.select_dtypes('object')
objects

,I avoid eating when am hungry,I cut my food into small pieces,"I particularly avoid food with high carbonhydrate(bread,rice,potatoes etc)",I take longer time than others to eat my meals,I avoid food and drink with sugar content,I like my stomach empty,I fast to avoid eating
0,Always,Always,Always,Always,Always,Always,Always
1,Always,Always,Always,Always,Always,Always,Always
2,Always,Always,Always,Always,Always,Always,Always
3,Always,Always,Always,Always,Always,Always,Always
4,Always,Always,Always,Always,Always,Often,Always
...,...,...,...,...,...,...,...
402,Never,Never,Never,Never,Never,Never,Never
403,Never,Never,Never,Never,Never,Never,Never
404,Never,Never,Never,Never,Never,Never,Never
405,Never,Never,Never,Never,Never,Never,Never
406,Never,Never,Never,Never,Never,Never,Never

In [11]:
# The object datatypes will be converted to numerical category in order to pass it to our algorithm

from sklearn import preprocessing as pp

In [12]:
# Instanciation

label_encoder = pp.LabelEncoder()
label_encoder

LabelEncoder()

In [9]:
# Get the columns of the object datatypes as a list because i want to use for loop iteration

obj = objects.columns.to_list()
obj

['I avoid eating when am hungry',
 'I cut my food into small pieces',
 'I particularly avoid food with high carbonhydrate(bread,rice,potatoes etc)',
 'I take longer time than others to eat my meals',
 'I avoid food and drink with sugar content',
 'I like my stomach empty ',
 'I fast to avoid eating']

In [13]:
for column in obj:
    objects[column] = label_encoder.fit_transform(objects[column])

In [14]:
objects

,I avoid eating when am hungry,I cut my food into small pieces,"I particularly avoid food with high carbonhydrate(bread,rice,potatoes etc)",I take longer time than others to eat my meals,I avoid food and drink with sugar content,I like my stomach empty,I fast to avoid eating
0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0
4,0,0,0,0,0,4,0
...,...,...,...,...,...,...,...
402,1,2,1,1,1,2,2
403,1,2,1,1,1,2,2
404,1,2,1,1,1,2,2
405,1,2,1,1,1,2,2
406,1,2,1,1,1,2,2

In [17]:
df1 = numeric.merge(objects, right_index=True, left_index=True)
df1

,Class,Age,I avoid eating when am hungry,I cut my food into small pieces,"I particularly avoid food with high carbonhydrate(bread,rice,potatoes etc)",I take longer time than others to eat my meals,I avoid food and drink with sugar content,I like my stomach empty,I fast to avoid eating
0,1,14,0,0,0,0,0,0,0
1,1,14,0,0,0,0,0,0,0
2,1,14,0,0,0,0,0,0,0
3,1,14,0,0,0,0,0,0,0
4,1,14,0,0,0,0,0,4,0
...,...,...,...,...,...,...,...,...,...
402,0,23,1,2,1,1,1,2,2
403,0,23,1,2,1,1,1,2,2
404,0,23,1,2,1,1,1,2,2
405,0,23,1,2,1,1,1,2,2
406,0,23,1,2,1,1,1,2,2

### Haven gotten our dataframe in numerical format acceptable by any algorithm for predictions, let's get our featues and label

In [31]:
X = df1.iloc[:, 1:].values
X

array([[14,  0,  0, ...,  0,  0,  0],
       [14,  0,  0, ...,  0,  0,  0],
       [14,  0,  0, ...,  0,  0,  0],
       ...,
       [23,  1,  2, ...,  1,  2,  2],
       [23,  1,  2, ...,  1,  2,  2],
       [23,  1,  2, ...,  1,  2,  2]], dtype=int64)

In [32]:
y = df['Class']
y

0      1
1      1
2      1
3      1
4      1
      ..
402    0
403    0
404    0
405    0
406    0
Name: Class, Length: 407, dtype: int64

In [33]:
# let's split the dataframe for Training and testing

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state=42)

In [34]:
# you can print them out to check what they look like
y_train

331    0
3      1
18     1
131    1
118    1
      ..
71     1
106    1
270    0
348    0
102    1
Name: Class, Length: 325, dtype: int64

## Getting our algorithm

for comparison purpuse, I'm going to train 3 different models for this job and we're going to adopt the one that did the best job

we'll use th;
1. decision tree
2. support vector machine
3. k-nearest neighbours

In [35]:
# Let's import the models we want to use in our data, train the model to make predictions

from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

In [36]:
# Instanciation

SVC_model = SVC()


# KNN model requires you to specify n_neighbors,
# the number of points the classifier will look at to determine what class a new point belongs to
# KNN_model = KNeighborsClassifier(n_neighbors=5) by default, n_neighbors is 5, so we leave at that first
KNN_model = KNeighborsClassifier()

DTC_model = DecisionTreeClassifier()

In [37]:
# Now let's fit the classifiers:

# Now train the model using the fit method. In the fit method, pass training datasets in it. 
# x_train and y_train are the training datasets.

SVC_model.fit(X_train, y_train)

KNN_model.fit(X_train, y_train)

DTC_model.fit(X_train, y_train)

DecisionTreeClassifier()

## The call has trained the model, so now we can predict and store the prediction in a variable:

In [38]:
SVC_pred = SVC_model.predict(X_test)

KNN_pred = KNN_model.predict(X_test)

DTC_pred = DTC_model.predict(X_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

In [39]:
print('SVC_pred')
print(SVC_pred)
print('________________________________________')
print()

print('KNN Prediction')
print(KNN_pred)
print('________________________________________')
print()

print('DTC Prediction')
print(DTC_pred)

SVC_pred
[1 1 0 0 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 1 1 1 1 0 0 0
 0 1 0 0 0 1 1 0 0 1 0 0 1 1 1 1 0 0 0 1 1 0 0 0 1 1 1 0 1 0 0 1 0 0 0 1 0
 1 1 0 1 0 0 0 0]
________________________________________

KNN Prediction
[1 0 0 1 1 1 1 0 0 0 0 1 0 0 1 1 1 0 1 0 1 0 0 1 0 0 1 0 1 1 1 1 1 1 0 0 1
 0 1 0 0 0 1 1 1 0 1 0 1 1 1 1 1 1 0 0 1 1 1 0 1 1 0 1 0 0 0 1 0 0 1 0 1 1
 1 0 1 1 0 0 0 0]
________________________________________

DTC Prediction
[1 0 0 0 1 1 1 0 0 0 0 1 0 0 1 1 1 0 1 0 1 0 0 1 0 0 1 0 1 1 1 1 1 1 0 0 1
 0 1 0 0 0 1 1 1 0 1 0 1 1 1 1 1 1 0 0 1 1 1 0 1 1 0 1 0 0 0 1 0 0 0 0 1 1
 1 1 1 1 0 0 0 0]

### We should now evaluate how the classifier performed. There are multiple methods of evaluating a classifier's performance.

#### In Scikit-Learn you just pass in the predictions against the ground truth labels which were stored in your test labels:

In [40]:
# Accuracy score is the simplest way to evaluate the classification perfomance

from sklearn.metrics import accuracy_score

print(f'SVC Accuracy score: {round(accuracy_score(SVC_pred, y_test), 2)}')
print(f'KNN Accuracy Score: {round(accuracy_score(KNN_pred, y_test), 2)}')
print(f'DTC Accuracy score: {round(accuracy_score(DTC_pred, y_test), 2)}')

SVC Accuracy score: 0.74
KNN Accuracy Score: 0.94
DTC Accuracy score: 0.95

So the KNN and DecissionTree did the best job here

### But Confusion Matrix and Classification Report give more details about performance so let's call them to give us details

In [41]:
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import classification_report

In [42]:
print(confusion_matrix(SVC_pred, y_test))
print()
print(confusion_matrix(KNN_pred, y_test))
print()
print(confusion_matrix(DTC_pred, y_test))

[[33 17]
 [ 4 28]]

[[35  3]
 [ 2 42]]

[[36  3]
 [ 1 42]]

In [43]:
print(f'Classification Report of Support Vector Classifier')
print(classification_report(SVC_pred, y_test))
print()
print(f'Classification Report of K-Nearest Neighbours')
print(classification_report(KNN_pred, y_test))
print()
print(f'Classification Report of Decision Tree Classifier')
print(classification_report(DTC_pred, y_test))

Classification Report of Support Vector Classifier
              precision    recall  f1-score   support

           0       0.89      0.66      0.76        50
           1       0.62      0.88      0.73        32

    accuracy                           0.74        82
   macro avg       0.76      0.77      0.74        82
weighted avg       0.79      0.74      0.75        82


Classification Report of K-Nearest Neighbours
              precision    recall  f1-score   support

           0       0.95      0.92      0.93        38
           1       0.93      0.95      0.94        44

    accuracy                           0.94        82
   macro avg       0.94      0.94      0.94        82
weighted avg       0.94      0.94      0.94        82


Classification Report of Decision Tree Classifier
              precision    recall  f1-score   support

           0       0.97      0.92      0.95        39
           1       0.93      0.98      0.95        43

    accuracy                           0.95        82
   macro avg       0.95      0.95      0.95        82
weighted avg       0.95      0.95      0.95        82

In [49]:
df1.head(100)

,Class,Age,I avoid eating when am hungry,I cut my food into small pieces,"I particularly avoid food with high carbonhydrate(bread,rice,potatoes etc)",I take longer time than others to eat my meals,I avoid food and drink with sugar content,I like my stomach empty,I fast to avoid eating
0,1,14,0,0,0,0,0,0,0
1,1,14,0,0,0,0,0,0,0
2,1,14,0,0,0,0,0,0,0
3,1,14,0,0,0,0,0,0,0
4,1,14,0,0,0,0,0,4,0
...,...,...,...,...,...,...,...,...,...
95,1,18,5,4,4,3,3,5,6
96,1,18,5,4,4,3,3,5,6
97,1,18,5,4,4,3,3,5,6
98,1,18,5,4,4,3,3,5,6
99,1,18,5,4,4,3,3,5,6

In [50]:
# Okay we are done, let us do some manual input to see things for ourselves
# let me test row 95

preds = []

for i in range(len(df1.iloc[:, 1:].columns)):
    val = float(input(f'Enter the value for the {df1.iloc[:, 1:].columns[i]} >>> '))
    preds.append(val)
    
print()
print(f'Support Vector Prediction {SVC_model.predict([preds])}')

print()
print(f'K-Nearest Neighbour Prediction {KNN_model.predict([preds])}')

print()
print(f'Decision Tree classifier Prediction {DTC_model.predict([preds])}')

Enter the value for the Age >>> 18
Enter the value for the I avoid eating when am hungry >>> 5
Enter the value for the I cut my food into small pieces >>> 4
Enter the value for the I particularly avoid food with high carbonhydrate(bread,rice,potatoes etc) >>> 4
Enter the value for the I take longer time than others to eat my meals >>> 3
Enter the value for the I avoid food and drink with sugar content >>> 3
Enter the value for the I like my stomach empty  >>> 5
Enter the value for the I fast to avoid eating >>> 6

Support Vector Prediction [1]

K-Nearest Neighbour Prediction [1]

Decision Tree classifier Prediction [1]

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

All my model predicted correctly, but KNN and Decision Tree are to be trusted the most here


***Thanks From Ohachu Chisom***